<?php

use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('municipios')->insert([
            ['isla_id' => 1, 'nombre' => 'FRONTERA'],
            ['isla_id' => 1, 'nombre' => 'PINAR DE EL HIERRO, EL'],
            ['isla_id' => 1, 'nombre' => 'VALVERDE'],
            ['isla_id' => 2, 'nombre' => 'ANTIGUA'],
            ['isla_id' => 2, 'nombre' => 'BETANCURIA'],
            ['isla_id' => 2, 'nombre' => 'OLIVA, LA'],
            ['isla_id' => 2, 'nombre' => 'PÁJARA'],
            ['isla_id' => 2, 'nombre' => 'PUERTO DEL ROSARIO'],
            ['isla_id' => 2, 'nombre' => 'TUINEJE'],
            ['isla_id' => 3, 'nombre' => 'AGAETE'],
            ['isla_id' => 3, 'nombre' => 'AGÜIMES'],
            ['isla_id' => 3, 'nombre' => 'ALDEA DE SAN NICOLÁS, LA'],
            ['isla_id' => 3, 'nombre' => 'ARTENARA'],
            ['isla_id' => 3, 'nombre' => 'ARUCAS'],
            ['isla_id' => 3, 'nombre' => 'FIRGAS'],
            ['isla_id' => 3, 'nombre' => 'GÁLDAR'],
            ['isla_id' => 3, 'nombre' => 'INGENIO'],
            ['isla_id' => 3, 'nombre' => 'MOGÁN'],
            ['isla_id' => 3, 'nombre' => 'MOYA'],
            ['isla_id' => 3, 'nombre' => 'PALMAS DE GRAN CANARIA, LAS'],
            ['isla_id' => 3, 'nombre' => 'SAN BARTOLOMÉ DE TIRAJANA'],
            ['isla_id' => 3, 'nombre' => 'SANTA BRÍGIDA'],
            ['isla_id' => 3, 'nombre' => 'SANTA LUCÍA DE TIRAJANA'],
            ['isla_id' => 3, 'nombre' => 'SANTA MARÍA DE GUÍA DE GRAN CANARIA'],
            ['isla_id' => 3, 'nombre' => 'TEJEDA'],
            ['isla_id' => 3, 'nombre' => 'TELDE'],
            ['isla_id' => 3, 'nombre' => 'TEROR'],
            ['isla_id' => 3, 'nombre' => 'VALLESECO'],
            ['isla_id' => 3, 'nombre' => 'VALSEQUILLO DE GRAN CANARIA'],
            ['isla_id' => 3, 'nombre' => 'VEGA DE SAN MATEO'],
            ['isla_id' => 4, 'nombre' => 'AGULO'],
            ['isla_id' => 4, 'nombre' => 'ALAJERÓ'],
            ['isla_id' => 4, 'nombre' => 'HERMIGUA'],
            ['isla_id' => 4, 'nombre' => 'SAN SEBASTIÁN DE LA GOMERA'],
            ['isla_id' => 4, 'nombre' => 'VALLE GRAN REY'],
            ['isla_id' => 4, 'nombre' => 'VALLEHERMOSO'],
            ['isla_id' => 5, 'nombre' => 'BARLOVENTO'],
            ['isla_id' => 5, 'nombre' => 'BREÑA ALTA'],
            ['isla_id' => 5, 'nombre' => 'BREÑA BAJA'],
            ['isla_id' => 5, 'nombre' => 'FUENCALIENTE DE LA PALMA'],
            ['isla_id' => 5, 'nombre' => 'GARAFÍA'],
            ['isla_id' => 5, 'nombre' => 'LLANOS DE ARIDANE, LOS'],
            ['isla_id' => 5, 'nombre' => 'PASO, EL'],
            ['isla_id' => 5, 'nombre' => 'PUNTAGORDA'],
            ['isla_id' => 5, 'nombre' => 'PUNTALLANA'],
            ['isla_id' => 5, 'nombre' => 'SAN ANDRÉS Y SAUCES'],
            ['isla_id' => 5, 'nombre' => 'SANTA CRUZ DE LA PALMA'],
            ['isla_id' => 5, 'nombre' => 'TAZACORTE'],
            ['isla_id' => 5, 'nombre' => 'TIJARAFE'],
            ['isla_id' => 5, 'nombre' => 'VILLA DE MAZO'],
            ['isla_id' => 6, 'nombre' => 'ARRECIFE'],
            ['isla_id' => 6, 'nombre' => 'HARÍA'],
            ['isla_id' => 6, 'nombre' => 'SAN BARTOLOMÉ'],
            ['isla_id' => 6, 'nombre' => 'TEGUISE'],
            ['isla_id' => 6, 'nombre' => 'TÍAS'],
            ['isla_id' => 6, 'nombre' => 'TINAJO'],
            ['isla_id' => 6, 'nombre' => 'YAIZA'],
            ['isla_id' => 7, 'nombre' => 'ADEJE'],
            ['isla_id' => 7, 'nombre' => 'ARAFO'],
            ['isla_id' => 7, 'nombre' => 'ARICO'],
            ['isla_id' => 7, 'nombre' => 'ARONA'],
            ['isla_id' => 7, 'nombre' => 'BUENAVISTA DEL NORTE'],
            ['isla_id' => 7, 'nombre' => 'CANDELARIA'],
            ['isla_id' => 7, 'nombre' => 'FASNIA'],
            ['isla_id' => 7, 'nombre' => 'GARACHICO'],
            ['isla_id' => 7, 'nombre' => 'GRANADILLA DE ABONA'],
            ['isla_id' => 7, 'nombre' => 'GUANCHA, LA'],
            ['isla_id' => 7, 'nombre' => 'GUÍA DE ISORA'],
            ['isla_id' => 7, 'nombre' => 'GÜÍMAR'],
            ['isla_id' => 7, 'nombre' => 'ICOD DE LOS VINOS'],
            ['isla_id' => 7, 'nombre' => 'MATANZA DE ACENTEJO, LA'],
            ['isla_id' => 7, 'nombre' => 'OROTAVA, LA'],
            ['isla_id' => 7, 'nombre' => 'PUERTO DE LA CRUZ'],
            ['isla_id' => 7, 'nombre' => 'REALEJOS, LOS'],
            ['isla_id' => 7, 'nombre' => 'ROSARIO, EL'],
            ['isla_id' => 7, 'nombre' => 'SAN CRISTÓBAL DE LA LAGUNA'],
            ['isla_id' => 7, 'nombre' => 'SAN JUAN DE LA RAMBLA'],
            ['isla_id' => 7, 'nombre' => 'SAN MIGUEL DE ABONA'],
            ['isla_id' => 7, 'nombre' => 'SANTA CRUZ DE TENERIFE'],
            ['isla_id' => 7, 'nombre' => 'SANTA ÚRSULA'],
            ['isla_id' => 7, 'nombre' => 'SANTIAGO DEL TEIDE'],
            ['isla_id' => 7, 'nombre' => 'SAUZAL, EL'],
            ['isla_id' => 7, 'nombre' => 'SILOS, LOS'],
            ['isla_id' => 7, 'nombre' => 'TACORONTE'],
            ['isla_id' => 7, 'nombre' => 'TANQUE, EL'],
            ['isla_id' => 7, 'nombre' => 'TEGUESTE'],
            ['isla_id' => 7, 'nombre' => 'VICTORIA DE ACENTEJO, LA'],
            ['isla_id' => 7, 'nombre' => 'VILAFLOR DE CHASNA']
        ]);
    }
}
